- app/build/resources/linux/debian/postinst
Some Ubuntu derivatives were not adding the appropriate PPA under the old "name based" system (elementary os, I'm looking at you...). The new system proposed here looks upstream to determine if it is okay to add.
> [PPA] Fixes issue where some Ubuntu derivatives would not add the appropriate PPA.

- README.md
The current links in the readme are pointed to an old folder structure; this PR fixes those paths to the current folder structure
> Update Mailspring paths for bundled themes/plugins

- app/internal_packages/message-list/lib/message-list.jsx
- app/internal_packages/message-list/styles/message-list.less
- app/src/config-schema.es6
* Implementing a descending order view of the message list
* Moved the option under the reading section in preferences and changed the wording of the option
* Forgot to update .gitignore
See https://github.com/nylas-mail-lives/nylas-mail/issues/20 and https://github.com/nylas-mail-lives/nylas-mail/pull/25
> Displaying conversation in a descending chronological order

- app/internal_packages/preferences/lib/tabs/workspace-section.jsx
In the General preferences tab, a code tag was visible inside of a note
> fix an escaped tag

- app/src/browser/mailspring-window.coffee
This removes the autohiding menu behaviour which results in users having to press alt to access the menu, as some key parts of the app are not easily accessible through the rest of the interfaces (such as preferences) it makes sense to keep the menu bar visible.
Fixes #81
> Do not auto-hide menu-bar

- app/spec/stores/contact-store-spec.coffee
- app/spec/stores/draft-factory-spec.es6
- app/src/flux/stores/contact-store.es6
- app/src/regexp-utils.coffee
(copied from my original PR: [nylas/nylas-mail #3636](https://github.com/nylas/nylas-mail/pull/3636))
Fixing [nylas/nylas-mail #3635](https://github.com/nylas/nylas-mail/issues/3635).
- Removed semicolon from the valid email check in `regexp-utils`.
- Added semicolon to the list of email separators, in `ContactStore.parseContactsInString()`
- Added test cases in `parseContactsInString()`, and also the `DraftFactory` (where the mailto click is handled & a new/draft email is created).
> Correctly parse multiple CCs/BCCs in mailto links

- app/src/browser/autoupdate-impl-base.es6
- app/src/browser/autoupdate-manager.es6
Handle internet errors of AutoUpdater on Linux instead of crashing.
Fix the EventListener so we log the error proprely.
Resolves: #140, #90
> Don't crash on startup if there is no internet connection

- app/internal_packages/message-list/lib/sidebar-participant-picker.jsx
The participant picker wasn't able to find a match for a participant with an undefined name, resulting in sending a null to _onFocusContact() instead of the desired Contact object.
Fixes: #177
> Fix picking participants with undefined names

- app/internal_packages/composer/lib/composer-view.jsx
- app/internal_packages/preferences/lib/tabs/keymaps/displayed-keybindings.js
- app/keymaps/base.json
I know @nickolasclarke has already added a PR for #92 but I thought I'd add mine to compare.
Feel free to close mine if it isn't useful.
> Added mod+shift+a shortcut for selecting an attachment in composer (fixes #92)

- app/internal_packages/composer-templates/assets/Welcome to Quick Replies.html
When a user first came on to the "Quick replies" preference pane, it would fire a message signed by the Nylas Team.
This is a really little modification but i hope to do more in the future. 
- Simon
> Removed "Nylas Team" from quick replies preferences

- app/src/app-env.es6
This is a workaround for #122 . On Linux there is an open issue with electron (See electron/electron#3490).
Since the electron has been outstanding for quite a while, I can't see it being fixed soon.
This workaround finds the window that mostly intersects the window and uses those bounds to centre the window.
It isn't perfect, but does a better job than splitting across multiple windows.
> Fix centering window on linux (fixes #122)

- app/internal_packages/notifications/lib/items/please-subscribe-notif.jsx
I understand your desire to push the user to buying the pro version of Mailspring but I think it is reasonable to make that message pop up at the start of each session but allow it to be dismissed. I cannot stand seeing this brightly colored box (theme dependent of course) every time I look at my email client and being unable to make it go away without paying $8 a month.
Before: ![before](https://i.imgur.com/UIusji1.png)
After: ![after](https://i.imgur.com/jSNtuYw.png)
> Allow subscription nag to be dismissed once per session

- app/keymaps/base.json
This seems to be universal behavior across a wide variety of apps & browsers, and I think this would improve the user's experience.  
Addresses issue #255.
> Use space/shift+space for additional pagedown/pageup

- app/src/config-schema.es6
- app/src/flux/stores/attachment-store.es6
Defaults to previous behavior, although it is possible that the previous default behavior doesn't make sense anymore.
Previous Behavior: If the last directory downloaded to (persistent across sessions) is the same directory we are downloading to, don't open it. Else, open it.
This configuration setting adds a way to disable this behavior and never open the directory, however this leads me to wonder if the previous behavior should now be changed to always open the directory (unless the configuration option is set to never open the directory) as the previous behavior seems odd to me.
This feature was requested in #156
> Add setting to disable opening containing folder on attachment download

- app/internal_packages/composer-signature/lib/constants.es6
- app/internal_packages/composer-signature/lib/preferences-signatures.jsx
- app/internal_packages/composer-signature/lib/templates.es6
Your Twitter profile image is now supported for use in your signature!
Also added by this commit:
* if you enter a Twitter handle with an "@" sign, we remove the "@" sign (`@mailspringapp` -> `mailspringapp`).
* if you enter your twitter handle as a URL, we convert it down to just your Twitter handle (`http://twitter.com/mailspringapp` -> `mailspringapp`).
The above changes allow the signature system to work better with regards to Twitter handles.
> [Signature] Twitter profile image support and better handling of Tiwtter handle.

- app/package.json
- app/src/error-logger.js
Native logging can be enabled with the `ELECTRON_ENABLE_LOGGING=1` environment variable.
> Remove nslog

- app/src/regexp-utils.es6
> Allow two points character inside urls for links

- app/internal_packages/ui-darkside/styles/darkside-threadlist.less
The darkside theme has a super small styling issue. It looks like this simple fix is all thats needed, let me know if something else needs to be done. 
Screenshot with the issue:
Screenshot with the issue fixed:
> Add padding to darkside theme search bar

- app/src/browser/mailspring-window.es6
Resolves Foundry376/Mailspring#1032, "Window icon is missing on Linux"
> Updates Linux icon location to pixmaps dir used by all major distros

- app/lang/fr.json
The rule editor was badly translated. Any was translated into "tous" which means "all' in this context. Which brings to the filter rules not understandable for french people. This fixes it
> Update weird translation in fr.json

- app/keymaps/base.json
See issue #1412. Adds a hotkey for the "Sync New Mail Now" command. Someone suggested `CTRL+R`, but that's already taken by reply, so I opted for `F5`, which I feel is pretty standard.
I almost feel silly submitting such a small change, but kudos on the app architecture for making something like this so easy to change!
> Add hotkey F5 for sync

- app/lang/cs.json
I have corrected two mistakes in czech translation of Mailspring.
1. "Čoskoro" is not a czech word, it is a Slovak word, so I have it replaced with czech equivalent of soon.
2. "Niť" is not good translation of thread. Better word is "vlákno" which is used in the rest of the application.
> Czech translation improved

- snap/snapcraft.template.yaml
There is an issue with the confluence of Electron, snaps, and Wayland that causes the snap packaged version of Mailspring to not launch when the desktop environment is using the Wayland compositor.
This fix follows the lead of other popular Electron apps (including Visual Studio Code and Atom) in working around the issue by falling back to XWayland. 
Fixes #1220.
Fixes #1067.
Fixes #982.
> Add DISABLE_WAYLAND to snapcraft.yaml

- app/lang/de.json
Haven't tested the change, but as all the other translations are using `%@` I guess it should be working :tada:
> Fixed placeholder typo in german translation

- app/src/date-utils.ts
Adds the ability to type in shorthand dates for Snooze. So instead of having to type out the entire string `4 hours`, you can just type `4h`, and the snoozer will intelligently interpret it.
This addition applies to Reminders, too:
> Add snooze date shorthand expander

- app/src/browser/window-manager.ts
fixes #1541 - just enable the frame and disable the toolbar, that's all.
> add frame and remove toolbar from calendar preview

- README.md
I started looking for MailSync and couldn't find the repository that was configured as a submodule in the Mailspring repo.
After a little searching, I found [issue #80](https://github.com/Foundry376/Mailspring/issues/80) that led me to the Roadmap file which explains why MailSync is closed source.
To make things easier for new contributors, I've updated the Readme to mention that MailSync is closed source, and to link to the roadmap which explains _why_.
> Update Readme re: MailSync's closed-source status.

- app/build/resources/linux/debian/control.in
Adds support for Ubuntu 20.04, which has no package named "python".
Should fix #1880 to make this app's `.deb` package insallable on fresh installs of Ubuntu 20.04.
> debian: Update "Depends:" to include python2

- app/build/resources/linux/mailspring.desktop.in
Changed GenericName value from "Mailspring" to "Mail Client" so that more useful info about the app is displayed on Linux, like in app launchers and taskbars (demonstrated in screenshots below).
Since the [convention](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys) is a short descriptive label of what the app is, and most other email clients like Thunderbird and KMail use "Mail Client", I also used "Mail Client".
**Pic 1:** Example of what other apps look like In the KDE taskbar:
**Pic 2:** What Mailspring looks like before change:
**Pic 3:** What Mailspring looks like after change (subtitle now displays useful info):
**Pic 4:** Mailspring in KDE Application Launcher before change
**Pic 5:** Mailspring in KDE Application Launcher …
> Made GenericName field more useful for app on Linux

- .gitignore
- app/internal_packages/message-list/lib/message-controls.tsx
I love this product and would like to contribute a little bit actively both in terms of internal functions and developing external plugins.
One thing I find really difficult is showing the original content of the email.
On my Ubuntu is very tricky enabling the secret context menu using the right button.
I thought that integrating it directly into the dropdown would not be bad, personally I find it very useful.
Maybe could be good prepend an icon too, as in other dropdown menu items.
> Added "Show original" in Message controls Actions Menu

- app/internal_packages/account-sidebar/lib/components/account-sidebar.tsx
- app/internal_packages/thread-list/lib/thread-list.tsx
- app/src/dom-utils.ts
As the title says, allows to override some layout properties using themes. For example:
```
mailspring-workspace {
// Allow wide sidebar.
--account-sidebar-max-width: 500;
// Effectively always 'narrow' multiline style.
--thread-list-narrow-style-width: 5000;
// Make taller previews, two lines.
--thread-list-item-height-narrow: 110;
}
```
The only issue I know of: some properties are only read on component creation/render time, for example row height. When switching a theme, only the CSS is getting applied, so some theme changes will only apply after reload or a major UI re-render.
> Read some layout properties from CSS instead of hardcoded values

- .gitignore
- .vscode/settings.json
Simply added DLLs and mailsync.exe to the .gitignore so that development on Windows is a bit friendlier.
> Ignores dll dependencies in git and VSCode

- app/src/components/composer-editor/composer-editor.tsx
This adds a check to look for text/uri-list entries on the clipboard to paste files when available. This is analogous to the existing mac and Windows checks.
To demonstrate:
- Open Thunar / Dolphin / Gnome Files on Linux
- Copy a file
- Paste into a mailspring compose window
Current behaviour:
- File path is pasted as text
Behaviour with this PR:
- File is pasted as an attachment
Thanks for maintaining a great email client on Linux!
> Fix paste files on Linux ( or other XDG desktops)

- app/internal_packages/onboarding/lib/mailcore-provider-settings.json
- app/internal_packages/onboarding/lib/mailspring-provider-settings.json
Hello,
I would like to add Hostinger to email providers in MailSpring. We have noticed that our users are using MailSpring email clients and we would like to offer automated email configuration function.
Hostinger International, Ltd is an employee-owned web hosting provider and internet domain registrar. Established in 2004, Hostinger now has over 29 million users, collectively with its subsidiaries in 178 countries.
> mailcore-provider-settings: Add Hostinger email provider

- app/src/components/composer-editor/composer-editor.tsx
This was implemented for the "Copy Image" function of browsers, which on Firefox and Chrome on Linux was tested to give item[0] as "text/html" and item[1] as a file.
This effectively worked in rich text mode anyway as it is able to paste text/html snippets, but was unable to work in plain text mode.
To demonstrate:
- "Copy Image" from Firefox or Chome
- Paste into a plaintext Mailspring composer
Current behaviour:
Does nothing
Behaviour with this PR:
Pastes image as an attachment.
Other changes of this PR:
Rich text composer will now inline-attach images that are pasted this way, I believe previously an \<img src=http://..> live ref would have been pasted as part of the text/html snippet. IMO this change is better behaviour as
- the end result for the user is the same ("my image appears …
> Allow data from "Copy Image.." to be pasted as an attachment (check all clipboard contents for Files, not just the first.)

- app/internal_packages/events/lib/event-header.tsx
- package-lock.json
- package.json
This probably also close #2024 #1546 and #1555 
The time displayed on the event-header component is wrong. In my case, it displayed the same time with the wrong timezone.
8AM-9AM New York timezone is actually 5.30PM-6.30PM Indian Standard Time (IST)
Based on the link from #1546, the bug was located in the [event-header.tsx](https://github.com/Foundry376/Mailspring/blob/33aba8f31fbbbcda924d335804801fcbb4e13f0d/app/internal_packages/events/lib/event-header.tsx#L108) file.
Added the following lines to see what is happening in the time conversion.
```js
console.log("Event enddate", icsEvent.endDate);
console.log("Event enddate zone", icsEvent.endDate.zone.toString());
console.log("Event enddate utc offset", icsEvent.endDate.utcOffset());
console.log("Event enddate JSDate", …
```
> Fixes #2039: wrong time in event header due to timezone mismatch

- app/build/resources/linux/debian/control.in
Should fix #2154, fix #2179, and fix #2198. Add libglib2.0-bin as an alternative dependency to gvfs-bin.
Resultant deb from current HEAD is here: https://github.com/akdor1154/Mailspring/releases/download/pr1/mailspring-1.7.8-amd64.deb . It installs here on Ubuntu 20.10 x86-64.
That deb is published purely to to allow others to test whether this dependency change works on their system. It is **not** a workaround to install Mailspring for you: it contains whatever is in master at this current point and is not a stable release.
> add libglib2-bin as alternative to gvfs-bin

- .appveyor.yml
- Appveyor CI does not have access to the secrets from forks
- Skip Appveyor CI if the PR is a non-release commit
- Fix #1365
> Fix Appveyor Status Failure

- app/internal_packages/onboarding/lib/account-providers.tsx
- app/lang/de.json
Fixes #2216 and adds a German translation for FastMail while improving existing German translations for iCloud and Yahoo account creation.
> Add information regarding app password type for FastMail

- app/internal_packages/events/lib/event-header.tsx
- app/package-lock.json
- app/package.json
While debugging different calendar invite issues, I noticed that the timezone of Google and Microsoft calendar invites could not be parsed correctly. This resolves the issue by adjusting some "uncommon" timezone formattings that are not understood by moment-timezone otherwise.
> Fix moment-timezone errors on calendar invites

- app/internal_packages/preferences/lib/tabs/workspace-section.tsx
Resolves #2265
This appears to be resolved now, at least on Ubuntu 20.04.
The only "oddity" about the fix is that it can take a moment for the checkbox to update its state. This is due to the fact that it pulls its state from an awaitable. It was already *supposed* to be, but the promise was not being awaited, which I believe was part of the problem.
While I was at it, I adjusted the pattern to match that of the Default Mail Client checkbox. That enabled me to find the problem better.
I'd appreciate any suggestions on how to improve this further. Otherwise, it should be ready to land.
> Make "Run on Startup" UI state persistent

- app/lang/de.json
- app/src/browser/system-tray-manager.ts
- app/src/config-schema.ts
While checking out this feature request, i noticed a bug: https://community.getmailspring.com/t/exit-on-x-button/207/5
When the "Show icon in menu bar / system tray" configuration is unchecked on linux, the tray icon does not disappear. When the configuration is checked again, a second tray icon appears. This fix resolves the issue by adding a workaround around a known electron issue: https://github.com/electron/electron/issues/17622
> Ensure that the tray icon does not appear multiple times on linux

- app/internal_packages/message-list/lib/message-list.tsx
- app/internal_packages/message-list/lib/sidebar-plugin-container.tsx
- app/internal_packages/thread-list/lib/thread-list.tsx
Decreasing the minimum width of certain elements allows the Mailspring window to be placed on half a screen (eg. snapping on Ubuntu using `Windows Key + Left Arrow`) even if the two coulmn layout is chosen. The minimum size is chosen so that the icons are still displayed correctly.
> Decrease container minWidth to allow window to snap to half a screen

- app/src/app-env.ts
This PR fixes #1953 and fixes #1978
For more information see: https://community.getmailspring.com/t/run-as-minimized-on-startup/57
I tested the behaviour on macOS thoroughly and could not determine any reason why there was an extra handling implemented here. In my opiniton it is save to remove this extra check.
> Ensure background start works in maximized mode

- app/internal_packages/preferences/lib/tabs/keymaps/displayed-keybindings.ts
- app/internal_packages/thread-list/lib/thread-list.tsx
- app/menus/darwin.js
- app/menus/linux.js
- app/menus/win32.js
> Able to Select All Unread Emails and Mark Them as Read With One Button

- app/internal_packages/account-sidebar/lib/sidebar-section.ts
- app/internal_packages/activity/package.json
- app/internal_packages/link-tracking/package.json
- app/internal_packages/onboarding/lib/newsletter-signup.tsx
- app/internal_packages/onboarding/lib/onboarding-store.ts
- app/internal_packages/onboarding/lib/page-authenticate.tsx
- app/internal_packages/open-tracking/package.json
- app/internal_packages/participant-profile/package.json
- app/internal_packages/preferences/lib/tabs/preferences-identity.tsx
- app/internal_packages/preferences/styles/preferences-identity.less
- app/internal_packages/send-reminders/package.json
- app/internal_packages/thread-list/lib/thread-list.tsx
- app/internal_packages/thread-sharing/package.json
- app/internal_packages/thread-snooze/lib/main.ts
- app/internal_packages/thread-snooze/lib/snooze-account-sidebar-extension.ts
- app/internal_packages/thread-snooze/package.json
- app/internal_packages/translation/package.json
- app/src/browser/application.ts
- app/src/browser/main.js
- app/src/components/billing-modal.tsx
- app/src/components/swipe-container.tsx
- app/src/components/webview.tsx
- app/src/flux/mailspring-api-request.ts
- app/src/flux/stores/identity-store.ts
- app/src/package-manager.ts
- app/src/package.ts
- app/static/db-migration.html
- app/static/db-vacuum.html
- app/static/index.html
Hey folks - this one has been a long time coming, but here we go!
This PR makes the Mailspring ID optional. When you launch the app for the first time, you can now bypass the Mailspring ID setup screen by choosing "Not Now" on the create an account page (it's at the bottom beneath sign in). The app reminds you that some features will be disabled, and then you're set!
When you opt out of the Mailspring ID, the value of `IdentityStore.identity()` is just `null`, rather than a placeholder identity or something like that. This required a few more code changes but it felt like the right approach.
On the mailsync side (also now GPLv3!), the tasks that sync message metadata to the cloud become no-ops and the metadata sync worker is disabled, but that's about all that had to change there. There …
> Make Mailspring ID optional, allow plugins to indicate dependency on synced metadata

- app/internal_packages/send-reminders/styles/send-reminders.less
This resolves #2019 / https://community.getmailspring.com/t/header-toggle-control-in-wrong-place-for-reminders/903
> Correctly place the header-toggle-control for e-mails with reminders

- app/internal_packages/contacts/lib/ContactDetailRead.tsx
This resolves #2018 / https://community.getmailspring.com/t/contact-birthdays-without-a-year-appears-as-invalid/902
> Construct a birthday year if none provided and hide its display

- app/src/services/autolinker.ts
When in email content is adaptivecard as JWT it can be 50kB of text and regex processing tooks ~8s. Limited regex search to 5 000 characters
> fixed regex issue with long processing

- .gitignore
- .gitmodules
- .travis.yml
- snap/.snapcraft/state
- snap/snapcraft.yaml
This is some cleanup work on travis-ci to be used as base for adding further changes to the snap code (as we need newer snapcraft via lxd to do that).
The cleanup eventually allowed to port the snap to use [core18](https://snapcraft.io/core18) and gnome-3.34 as base for the snap content (that reduces space and uses better desktop integration, especially with file picker).
We also may move to core20, but we'd need to build it under focal, and this may be unwanted (unless we do a full snap build alone)
An example run is at: https://travis-ci.com/github/3v1n0/Mailspring/jobs/498546128
While a built snap is: https://transfer.sh/1oyK9/mailspring_1.9.0_amd64.snap
> CI: cleanup code, use xenial container as base and build snap using core18

- app/internal_packages/thread-list/lib/main.ts
- app/internal_packages/thread-list/lib/thread-list-vertical.tsx
- app/lang/de.json
This resolves the issue, as the ThreadListEmptyFolderBar registeres to be displayed at the `WorkspaceStore.Location.ThreadList`, which happened to exist twice in the ThreadListVertical view. This changes removes the duplicate location, so that the ThreadListEmptyFolderBar is only displayed once at the correct location.
Also improve the German translation slightly.
> Prevent strange layout bug for trash / spam folders on vertical layout

- app/src/components/scenario-editor-models.ts
- app/src/components/scenario-editor-row.tsx
- app/src/flux/actions.ts
- app/src/flux/stores/draft-store.ts
- app/src/mail-rules-processor.ts
- app/src/mail-rules-templates.ts
This pr adds a new forward action to the mail rules. I use this functionality a lot to automatically send invoices to my printer & bookkeeper, and needed it before migrating to Mailspring, but I'm not sure if it's actually something that should be in the master build.
> feat(MailRule): add 'forward' action to mail rules

- app/src/system-start-service.ts
Currently, the `--background` flag of the plist autostart file on macos is ignored as it is treated as the filename of the command to start (which should be mailspring) and not as an argument. Therefore Mailspring is started in foreground mode instead of background mode.
For more information see: https://apple.stackexchange.com/questions/110644/getting-launchd-to-read-program-arguments-correctly
> Ensure that mailspring is correctly started in the background on macos

- app/internal_packages/category-mapper/lib/preferences-category-mapper.tsx
- app/internal_packages/onboarding/lib/mailspring-provider-settings.json
- app/internal_packages/onboarding/lib/onboarding-helpers.ts
- app/internal_packages/onboarding/lib/onboarding-store.ts
- app/internal_packages/onboarding/lib/page-account-settings-imap.tsx
- app/internal_packages/onboarding/styles/onboarding.less
- app/src/browser/application.ts
- app/src/flux/actions.ts
- app/src/flux/models/account.ts
- app/src/flux/stores/account-store.ts
resolve #429 https://community.getmailspring.com/t/protonmail-bridge-imap/485
Foundry376/Mailspring-Sync#3
> ProtonMail Bridge IMAP integration

- app/internal_packages/onboarding/lib/mailspring-provider-settings.json
Protonmail used to allow `.ch` domain for new users' email domain. I also have one. Without this, no default Folder is chosen when creating protonmail account and protonmail fix [2323](https://github.com/Foundry376/Mailspring/pull/2323) does not work.
> Add protonmail.ch domain into onboarding defaults

- app/build/resources/linux/mailspring.appdata.xml.in
This PR solves these Appdata file errors:
- Doesn't contain right name for desktop file
- Doesn't have release tags
**NOTE:**
- The release tag needs to be added whenever a new release is created.
> Add releases info and squeeze content_rating to fix flatpak build

- app/internal_packages/onboarding/lib/onboarding-helpers.ts
- app/internal_packages/onboarding/lib/page-account-settings-imap.tsx
Since [RFC 8314](https://datatracker.ietf.org/doc/html/rfc8314) _Cleartext Considered Obsolete: Use of Transport Layer Security (TLS) Email Submission and Access_, SMTP with Implicit TLS over port 465 is preferred over SMTP with STARTTLS over port 587.
See [Section 3](https://datatracker.ietf.org/doc/html/rfc8314#section-3):
> Previous standards for the use of email protocols with TLS used the STARTTLS mechanism
> (...)
> Although this mechanism has been deployed, an alternate mechanism where TLS is negotiated immediately at connection start on a separate port (referred to in this document as "Implicit TLS") has been deployed more successfully.
> To encourage more widespread use of TLS and to also encourage greater consistency regarding how TLS is used, **this specification now recommends …
> Default to SSL / TLS on port 465 for SMTP, per RFC 8314

- app/internal_packages/thread-list/lib/thread-toolbar-buttons.tsx
[Related issue](https://community.getmailspring.com/t/remove-and-show-previous-shortcut-fails-on-last-email/930)
> Go back to inbox after "Remove and show next/previous" for last email

- app/src/flux/models/contact.ts
Resolves: #2359
Currently, the full E-Mail address as the Sender is only shown in addition to "You" when you are viewing the e-mail in the "Inbox" of all e-mail accounts and not when viewing a single account's inbox. Show this e-mail regardless of the e-mail inbox.
> Adjust account label check

- app/src/quickpreview/index.ts
This replaces the `exec` method when using the Quick Preview functionality on MacOS with `execFile` in order to improve security.
> Replace exec with execFile in MacOS Quick Preview

- app/internal_packages/onboarding/lib/onboarding-helpers.ts
ref: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code
> enable support multi o365 account to choose which to auth

- app/internal_packages/onboarding/lib/onboarding-helpers.ts
- Add a platform
- Choose "Mobile and desktop applications"
- use 'node-fetch' instead of 'fetch' package
---
[💕](https://emojipedia.org/symbols/) Love to use MailSpring so much [🫶](https://emojipedia.org/heart-hands/) Nice App [🥹](https://emojipedia.org/face-holding-back-tears/)
> WIP: Enable longer-alive refresh token from o365

- app/src/browser/main.js
Fixes: https://github.com/Foundry376/Mailspring/issues/2408
It seems like the newer electron versions pass some extra arguments to the `second-instance` event which broke the sendto functionality.
> Fix sendto functionality by correctly handling electron internal options

- app/internal_packages/thread-list/lib/thread-list-vertical.tsx
There is always overflow, because of the toolbar, at some point the renderer moves it to the top which hides messages.
I have made the area a flexbox to stack the items correctly and prevent the overflow
> Fix the vertical overflow bug (Community - 1677, 3507, 4378 & 4557)

- app/internal_packages/message-list/lib/message-item-body.tsx
Applied a fix to resolve the broken `[Message Clipped - Show All]` link. Fixing community issues [4731](https://community.getmailspring.com/t/clipped-long-messages-do-not-expand/4731) & [4899](https://community.getmailspring.com/t/clipped-long-messages-do-not-expand/4899)
> Fix `[Message Clipped - Show All]` link - Community #4731 & #4899

- .gitignore
- app/internal_packages/message-list/lib/message-list.tsx
- app/internal_packages/message-list/lib/message-participants.tsx
- app/internal_packages/undo-redo/lib/undo-redo-toast.tsx
- app/internal_packages/undo-redo/styles/index.less
- app/lang/en.json
- app/src/date-utils.ts
- app/src/flux/stores/database-store.ts
_Sorry, didn't realise rename would close [original PR](https://github.com/Foundry376/Mailspring/pull/2419)_
---
Made a few UX improvements:
- The send later delay can be skipped by clicking the new `Send now instead` button (localization required)
- If there is a range selection in the subject line then a context menu pops up on right-click (for those that are allergic to keyboard shortcuts 😂)]
- Dates/times used are now in a localised format, rather than the American one
- Message participant tweaks:
- you can now open the context menu on the name or email, not just the email
- you don't need to expand the participants to open the context menu
- name is shown over the email for `Email "Name else Email"` context menu item
- added `Copy "Email"` to the context menu when nothing is …
> Some UX improvements

- app/internal_packages/composer/lib/composer-view.tsx
- app/internal_packages/preferences/lib/tabs/preferences-general.tsx
- app/package-lock.json
- app/src/flux/stores/draft-editing-session.ts
Hey, this is my first stab at open source contributions. I'm working on [this feature suggestion](https://community.getmailspring.com/t/make-composer-recipient-name-warnings-optional-add-dont-warn-me-again-option/630). So far I've split the `DraftSession::validateDraftForSending` by making a separate `validateDraftRecipients` as described by @bengotow. I will start working on the portion of adding a button to ignore warnings for that email, but wanted to check whether my approach for the first part is acceptable or requires tweaking.
> Making composer recipient name warnings optional

- app/internal_packages/message-list/lib/message-participants.tsx
This was changed from a template string to JSX, but the escape format was not updated. There is also now a missing space before the word "and".
Before:
After:
> Fix "and X more" display in message contacts

- app/src/mailsync-process.ts
Fixed start crash, caused by incorrect module being referenced
Reference: https://community.getmailspring.com/t/mailspring-1-10-5-crashes-at-start-on-debian-11/5324
> Fix for start crash - Community#5324

- app/src/date-utils.ts
12pm is now shown instead of 0pm
---
Not I needed to use `h23` instead of `h24` else midnight would have been shown as `24:01` - or similar
> Corrected 0pm to 12pm - Community#5936

- app/package-lock.json
- app/src/components/attachment-items.tsx
- app/src/components/composer-editor/inline-attachment-plugins.tsx
- app/static/style/components/attachment-items.less
Add image resizing to the composer - closes [Community#729](https://community.getmailspring.com/t/resizing-image-in-composer/729)
---
- You can now resize images within the composer
- by default, it will retain the original ratio (holding <kbd>Shift</kbd> = freeform)
- Adjusted the margins and positions of the image in the composer so it matches the email viewer  
_before it was padded and top-aligned then, in the viewer, it would have no padding and be base-aligned - meaning what you see is not what they get 😉_
> Composer image resize - Community#729

- app/src/browser/application.ts
This pull request adds a "New email" quick action on the contextual menu of the dock icon on MacOS.
This is how it would look (here Mailspring is in Spanish):
> Add new email shortcut on MacOS dock icon contextual menu

- app/build/resources/linux/mailspring.appdata.xml.in
Related to https://github.com/flathub/com.getmailspring.Mailspring/pull/21
Flatpak checks for <id>...</id> tag but due to incorrect formatting it cannot find it.
> fix: mailspring appdata formatting

- app/src/regexp-utils.ts
Currently, URLs that look like:
`http://example.com/something:with:colons`
Only parses `http://example.com/something` as a link.  This fixes that, as the URLs above are allowed.
This does not parse a trailing `:`, so that something like this:
`http://example.com/something: This is a link to something`
The link will be parsed to `http://example.com/something` and not to `http://example.com/something:`
> Fix: Colons are allowed in URL paths.

- app/internal_packages/category-picker/lib/move-picker-popover.tsx
- app/src/components/menu.tsx
The idea was to improve UX when moving emails between folders. Current implementation requires user to correctly type in the whole folder path (including all the parent folders), which can be rather difficult if the folder hierarchy has several layers. My solution was inspired by a Thunderbird plugin "Manage Emails/ Nostalgy++".
On the technical side changes include:
- new optional callback 'onExpand' from 'Menu' component. It is fired if the user has highlighted a folder and pressed 'Tab' or 'ArrowRight' on it (to expand/drill down into);
- 'MovePickerPopover' code to set up the callback on 'Menu' and to handle its response by passing the highlighted folder name to the input field, thus narrowing the search.
I understand that this change could be controversial as it is suddenly …
> Add Menu action allowing it to be used as AutoSuggest

- app/menus/darwin.js
- app/menus/linux.js
- app/menus/win32.js
Should fix the help menu search missing
I haven't been able to test if because of this error, would be great if someone could let me know how to fix it:
> Fix help menu search

- app/src/date-utils.ts
The issue addressed here is the inability of the current scheduling feature to interpret strings like "123" or "1234" as a valid time for scheduling emails.
Feature Proposal: https://community.getmailspring.com/t/intuitive-time-parsing-for-email-scheduling/6991
To resolve this, I updated the date parsing logic to handle both 3 and 4 digit time input strings. The added logic will check the length of the string before slicing and inserting a colon to separate the hours and minutes if present.
For example, it will interpret "123" as "1:23" and "1234" as "12:34".
closes #2462
> Intuitive Time Parsing for Email Scheduling

- app/lang/da.json
- app/lang/de.json
- app/lang/lt.json
- app/lang/pl.json
- app/src/mail-rules-templates.ts
This PR adds a "Reply to" filter to the email rules. In additions, the localization for the recipient filter is slightly adjusted (colons removed) in some languages to match the label in all other languages. Otherwise this filter label is the only one with a colon in the filter view which looks very strange.
The filter rule is successfully tested. :)
This will resolve https://community.getmailspring.com/t/reply-to-as-a-filter-rule-option/967
> Add "Reply to" filter to email rules 

- app/internal_packages/thread-snooze/lib/snooze-utils.ts
This will ensure that the snooze label is unambiguous with regards to day/year. I also removed the 'until' from the string as it was not properly localized anyways and to ensure that the label does not need too much space.
Current Labels (German date formatting):
New Labels (German date formatting):
> feat: Make snooze label unambiguous

- app/build/resources/linux/debian/control.in
The mailspring debian package cannot be installed on Ubuntu 23.10 anymore due to the dprecated gconf packages being not available anymore. This PR removes this deprecated dependency.
For more information see:
- https://github.com/electron/electron/issues/2727
- https://github.com/mattermost/desktop/issues/2853
> chore: remove deprecated linux dependency gconf2

- app/build/sqlite-amalgamation/README.md
- app/build/sqlite-amalgamation/shell.c
- app/build/sqlite-amalgamation/sqlite3.h
- app/build/sqlite-amalgamation/sqlite3ext.h
- app/internal_packages/onboarding/lib/onboarding-constants.ts
- app/package-lock.json
- app/package.json
- app/script/mkdeb
- app/src/flux/stores/draft-factory.ts
- app/src/key-manager.ts
- package-lock.json
- package.json
I have updated electron to its latest version and bumped several connected dependencies as well.
Currently tested on Linux & Mac. I will try to test this on Windows within the next days and hope that everything there works as well.
> Upgrade electron to version 22

- app/build/resources/linux/mailspring.appdata.xml.in
to conform to AppStream metainfo standard
See https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots
This also allows creating Flatpaks for Flathub without having to unduly modify the metainfo file. See ugly `sed` hack currently needed in https://github.com/flathub/com.getmailspring.Mailspring/pull/43
> Fix screenshot reference

- app/build/resources/linux/redhat/mailspring.spec.in
Fixes https://community.getmailspring.com/t/rpm-1-15-conflicts-with-slack/9167
Based on https://github.com/microsoft/vscode/pull/116105
> rpm: do not generate build_id links

- app/build/resources/linux/redhat/mailspring.spec.in
Fixes [Unable to install RPM to Fedora 40](https://community.getmailspring.com/t/unable-to-install-rpm-to-fedora-40/8714), [Cannot install on Fedora 42 lsb-core not available](https://community.getmailspring.com/t/cannot-install-on-fedora-42-lsb-core-not-available/9658), [fedora: lsb-core-noarch is not available](https://github.com/Foundry376/Mailspring/issues/2496).
Small PR, probably a big discussion. 
It seems that in recent years there has been a shift in RHEL and LSB, where they seem to have actively removed it, not adhered to it, added WONTFIX, etc. Without getting into too much politics, here are some things on the topic.
https://access.redhat.com/solutions/6973382
https://web.archive.org/web/20240122163643/https://lists.linuxfoundation.org/pipermail/lsb-discuss/2023-February/008278 …
> Change lsb-core-noarch to be an optional dependency in the RPM package.
