Foundry376/Mailspring

app/keymaps/README.m
app/src/menu-manager.es6

Fixes nylas/nylas-mail#2305
I'm no longer using nylas mail, just recovering an old PR that might be still useful for current users of the forks! 🍻

Fix missing shortcuts in the application menu.

---

app/internal_packages/thread-snooze/lib/snooze-store.es6
app/internal_packages/thread-snooze/lib/snooze-utils.es6
app/src/config-schema.es6

Resolves #54. I put the setting under notifications since I couldn't think of a better place, happy to move if you have any other recommendations.

Add option for unsnoozed messages to show as unread.

---

app/src/regexp-utils.coffee

Fixes #269 
Dupe of #319 because the last one was closed due to my bad branch handling (Now using gitflow so that is not going to happen again)

Updated urlRegex to fix #269

---

app/src/browser/config-persistence-manager.es6

Restrict Mailspring config folder to 700 access mode

---

app/internal_packages/open-tracking/lib/open-tracking-composer-extension.es6

Added alt attribute to the "open tracking" image tag so it does not affect spam score.

Added alt attribute

---

README.md

Refs/Fixes https://github.com/Foundry376/Mailspring/issues/326
Add info for updating an existing Nylas theme for Mailspring.

Add info for updating an existing Nylas theme

---

app/lang/fr.json

Old translation was 
Date  = Rendez-vous amoureux

French translation changed (Date)

---

app/build/resources/linux/mailspring.desktop.in

Made the stupid mistake of grabbing them from another appdata file without checking if they were supported first... My bad... :sweat_smile:

Remove unsupported desktop categories

---

app/src/intl.es6

I've added the pt_BR option to the language menu.

Add pt_BR - intl.es6

---

app/internal_packages/preferences/lib/tabs/preferences-general.tsx

Added confirmation dialog before resetting accounts and settings

---

app/lang/zh-CN.json

add 1 new mandarin translation to zh_CN.json

translate a word mandarin

---

app/lang/pt-BR.json

Added new strings to the translation file, and corrected a few miswritten words.

pt-BR.json

---

CONTRIBUTING.md
app/internal_packages/notifications/lib/items/update-notification.tsx
app/internal_packages/notifications/specs/update-notification-spec.tsx
app/internal_packages/notifications/styles/styles.less

Allow cancel upgrade prompt

---

app/internal_packages/composer-signature/lib/constants.ts
app/internal_packages/composer-signature/lib/templates.tsx

#1611 
Can you add instagram.gif to https://www.getmailspring.com/signature-assets/instagram.gif

Add instagram signature link

---

app/internal_packages/thread-search/lib/thread-search-bar.tsx

Adjust search bar label based on the selected account

---

app/src/components/scenario-editor-models.ts

Fix bug when comparing empty string in mail rules

---

README.md

GitHub URLs are case sensitive

Fixed code of conduct link

---

app/src/browser/main.js

This resolves: https://community.getmailspring.com/t/attach-a-file-with-command-line-argument/182

Add documentation how to open composer window to help message

---

app/internal_packages/list-unsubscribe/lib/main.tsx

Add null check on email body to prevent cheerio exception

---

app/src/browser/main.js

Closes #2289.
Unfortunately only tested on Gnome and not within another desktop environment. I am happy to do further changes if necessary.

Handle nautilus-sendto links

---

app/internal_packages/message-list/lib/message-item.tsx

Closes #2292
Preview, how this looks:

Add subject to expanded message item for each email

---

app/keymaps/templates/Apple Mail.json
app/keymaps/templates/Gmail.json
app/keymaps/templates/Inbox by Gmail.json
app/keymaps/templates/Outlook.json

ref: https://community.getmailspring.com/t/snooze-shortcut/1631
gmail: `h`
inbox `gmail: h`
outlock: `ctrl+h`
apple mail: `mod+h`
Signed-off-by: Avelino <t@avelino.xxx>

add snooze shortcut

---

app/internal_packages/preferences/lib/tabs/keymaps/displayed-keybindings.ts

As requested [here](https://community.getmailspring.com/t/mark-as-spam-keyboard-shortcut/395).

Make "mark as spam" shortcut configurable

---

app/internal_packages/composer-signature/specs/signature-composer-dropdown-spec.jsx
app/internal_packages/composer/specs/send-action-button-spec.jsx
app/internal_packages/unread-notifications/specs/main-spec.es6
app/spec/autoupdate-manager-spec.ts
app/spec/components/tokenizing-text-field-spec.tsx
app/spec/services/autolinker-spec.ts
app/spec/services/quoted-html-transformer-spec.ts
app/spec/spec-runner/spec-runner.ts
app/spec/stores/feature-usage-store-spec.ts
app/spec/utils/utils-spec.ts

Discussion: https://community.getmailspring.com/t/cannot-test-mailspring-locally/2629/3
TODO:

Fix broken test runner and tests

---

app/src/browser/application.ts

Use correct directory when opening license file

---

app/internal_packages/onboarding/lib/onboarding-helpers.ts
app/src/browser/main.js

This resolves a bug, where it is no longer possible to authenticate to Office 365 e-mail accounts as described here: https://community.getmailspring.com/t/login-to-office-no-longer-working/4071

Fix login to Office 365 Accounts

---

app/internal_packages/message-list/lib/message-controls.tsx

This closes https://github.com/Foundry376/Mailspring/issues/2383.

Fix the show original functionality by correctly electron/remote

---

app/internal_packages/send-reminders/lib/send-reminders-popover-button.tsx

Adjust the order of the reminder button to prevent icons from jumping around

---

app/internal_packages/main-calendar/lib/core/calendar-constants.ts
app/internal_packages/main-calendar/lib/core/header-controls.tsx
app/internal_packages/main-calendar/lib/core/mailspring-calendar.tsx
app/internal_packages/main-calendar/lib/core/month-view.tsx
app/internal_packages/main-calendar/lib/core/week-view.tsx
app/internal_packages/main-calendar/styles/nylas-calendar.less

Added a UI to the `HeaderControl` component to switch between calendar views. Also added `HeaderControl` to Month view. Day button is currently commented out because Day view component doesn't exist yet. 
I'm getting familiar with the codebase with these small contributions so that I can make more meaningful contributions in the future. Let me know if there are any suggestions or improvements I can make with my code.

UI for switching calendar view (day/week/month)

---

app/internal_packages/list-unsubscribe/lib/main.tsx

Quicken the load on long threads - [Community #183](https://community.getmailspring.com/t/significant-lag-on-large-threads/183)
- ignore blockquote links
- cache results by `message.id` for ONLY the current session
----
Links inside blockquote should be ignored as: 1. we don't want to risk unsubscribing the sender from their forwarded email 2. if it's my email the link will be picked up in that message
As a state change triggers the re-rendering of the whole component, it makes the component do the work all over again - quite annoying when the element isn't even visible to the user yet. To stop this the component caches the results ONLY for the current session
_**Sidebar:** The below function is actually causing the lag. Possibly could be optimised - though I'm leaving it as this change …

Quicken load on long threads - Community#183

---

app/lang/de.json
app/lang/en.json
app/src/key-manager.ts

This will fix the keytar migration issue from https://github.com/Foundry376/Mailspring/pull/2464
I have run multiple tests and it seems to work for me in snap now. I still have a strange black background in the tray icon, but it is only visible before mailspring is running or when clicking on the tray icon. But this is definitely unreleated to the keytar issue. ;-)

fix: ensure smooth migration from keytar

---

app/src/flux/stores/draft-editing-session.ts

Fix bug where when an invalid recipient is chosen, the validation produces an error due to a wrong return value.

Fix bug on invalid recipient

---

app/internal_packages/message-list/styles/message-list.less

Fix subject overflow

---

app/internal_packages/composer-signature/lib/constants.ts
app/internal_packages/composer-signature/lib/templates.tsx

Added signature icons for Medium, GitHub and YouTube

Added signature icons for Medium, GitHub and YouTube
